DROP TABLE IF EXISTS USER;
CREATE TABLE USER ( 
    
    USERNAME VARCHAR(50) PRIMARY KEY NOT NULL, 
    PASSWORD VARCHAR(50), 
    LAST_LOGIN TIMESTAMP
    --FOREIGN KEY (USER_DETAILS) REFFERENCES USER_DETAILS(USER_DETAILS_ID)

    
) 